(package "zig-mode"
         "0.0.8"
         "A major mode for the Zig programming language")

(website-url "https://github.com/zig-lang/zig-mode")
(keywords "zig" "languages")

(package-file "zig-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "24.3")
(depends-on "reformatter")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
